### ISSUE TITLE
Consolidate with opentracing-contrib/java-redis-client

### ISSUE THREAD

**Issue by loganvolkers** [opentracing-contrib/java-redisson#1]
I'm not sure if this has already been evaluated, but there looks like there's another repo for the other java redis clients.

Centralizing this code in that repo may be useful?

**Comment by malafeev** [comment]
sounds reasonable
cc @tedsuo

**Comment by tedsuo** [comment]
SGTM!

**Comment by malafeev** [comment]
I will move it to `opentracing-contrib/java-redis-client`

**Comment by malafeev** [comment]
done

**Comment by loganvolkers** [comment]
Nice, that was some quick turnaround! 👏
